### ISSUE TITLE
ImportError: No module named xmltodict

### ISSUE THREAD

**Issue by ghillied-up** [sadponyguerillaboy/AST-Server#1]
i have installed all the required modules, but when i try to run it with python launcher, it gives following error.
ImportError: No module named xmltodict
 i am using python 3.8,

**Comment by sadponyguerillaboy** [comment]
> i have installed all the required modules, but when i try to run it with python launcher, it gives following error.
> ImportError: No module named xmltodict
> i am using python 3.8,

Have you tried: `pip3 install xmltodict`
I also reverted back to python 3.7 after finding lots of issues with modules having compatability issues with 3.8.  If you installed the module correctly for python3 and it's still not working, your issue is with xmltodict or python 3.8.

**Comment by ghillied-up** [comment]
i will give it a try on linux, right now i am using mac

**Comment by sadponyguerillaboy** [comment]
install python using homebrew, not via the python dmg installer.
https://brew.sh/
